name: Demo One API Development

on:
  push:
    branches: [ master ]
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the hello-docker Docker image
      run: |
        docker build . -t ghcr.io/santhoshprogrammer94/nest-mongo-starter-pulumi-demo/nest-pulumi-rnd:${{ github.sha }};
        docker push ghcr.io/santhoshprogrammer94/nest-mongo-starter-pulumi-demo/nest-pulumi-rnd:${{ github.sha }}